name: ChatFormatterPlugin
version: 1.0.0
main: ChatFormatter\Main
api: [5.0.0]
author: Himanshu
description: A plugin that formats chat messages with colors and custom formats.

permissions:
  chat.format.default:
    default: true
  chat.format.vip:
    default: op
