name: WelcomePlugin
version: 1.0.0
author: Himanshu
main: WelcomePlugin\Main
api: [5.0.0]

commands:
  welcome:
    description: Sends a welcome message
    usage: /welcome
    permission: welcome.command

permissions:
  welcome.command:
    description: Allows the player to use the /welcome command
    default: true
